export const NEXT_DEMO_REQUIRED_ENV_VARIABLES = [
  // base env
  "NEXT_DEMO_APP_NAME",
  "NEXT_DEMO_AUTH_SECRET",
  "NEXT_DEMO_AUTH_GOOGLE_ID",
  "NEXT_DEMO_AUTH_GOOGLE_SECRET",
  "NEXT_DEMO_AUTH_GITHUB_ID",
  "NEXT_DEMO_AUTH_GITHUB_SECRET",
  "NEXT_DEMO_EMAIL_ID",
  "NEXT_DEMO_EMAIL_PASSWORD",
  // NODE_ENV specific
  "NEXT_DEMO_DATABASE_URL",
  "NEXT_DEMO_AUTH_TRUSTED_ORIGINS",
  "NEXT_DEMO_AUTH_BASE_URL",
  "NEXT_DEMO_AUTH_BASE_PATH",
  "NEXT_DEMO_FRONTEND_URL",
  "NEXT_DEMO_AUTH_FRONTEND_VERIFY_EMAIL_PATH",
  "NEXT_DEMO_AUTH_FRONTEND_RESET_PASSWORD_PATH",
];
