export const NEXT_DEMO_REQUIRED_ENV_VARIABLES = [
  "NEXT_DEMO_DATABASE_URL",
  "NEXT_DEMO_AUTH_SECRET",
  "NEXT_DEMO_AUTH_URL",
  "NEXT_DEMO_AUTH_GOOGLE_ID",
  "NEXT_DEMO_AUTH_GOOGLE_SECRET",
  "NEXT_DEMO_AUTH_GITHUB_ID",
  "NEXT_DEMO_AUTH_GITHUB_SECRET",
  "NEXT_DEMO_EMAIL_CLIENT_ID",
  "NEXT_DEMO_EMAIL_SECRET",
  "NEXT_DEMO_EMAIL_REFRESH_TOKEN",
];
